### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by phdevpro** [dirtsimple/poste.io#25] opened 2022-12-11 11:21 UTC
Is there a way to have ARM support?

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec /init: exec format error
```

Thanks

**Comment by pjeby** [comment] 2022-12-11 21:49
Closing as duplicate of #22, #23, and #24.  Please search for existing issues before creating new ones.

**Closed as not planned by pjeby** 2022-12-11 21:49 UTC
