### ISSUE TITLE
Bind error

### ISSUE THREAD

**Issue by NhProGamer** [dirtsimple/poste.io#15] opened 2021-08-15 21:42 UTC
i have this error before the creation of the container
before container start all ports are unused

nginx: [emerg] bind() to dontgetmyip failed (99: Cannot assign requested address)
Error: bind(dontgetmyip, 4190) failed: Cannot assign requested address
Error: service(managesieve-login): listen(mail.nhsoul.fr, 4190) failed: Cannot assign requested address
Error: bind(dontgetmyip, 110) failed: Cannot assign requested address
Error: service(pop3-login): listen(mail.nhsoul.fr, 110) failed: Cannot assign requested address
Error: bind(dontgetmyip, 995) failed: Cannot assign requested address
Error: service(pop3-login): listen(mail.nhsoul.fr, 995) failed: Cannot assign requested address
Error: bind(dontgetmyip, 143) failed: Cannot assign requested address
Error: service(imap-login): listen(mail.nhsoul.fr, 143) failed: Cannot assign requested address
Error: bind(dontgetmyip, 993) failed: Cannot assign requested address
Error: service(imap-login): listen(mail.nhsoul.fr, 993) failed: Cannot assign requested address
Fatal: Failed to start listeners

**Comment by NhProGamer** [comment] 2021-08-15 21:49
it loops me the error with Poste.io administration available at https://176.183.46.58:443 or http://176.183.46.58:8081it loops me the error with Poste.io administration available at https://176.183.46.58:443 or http://176.183.46.58:8081
![qvdsqvqsdfqsvfqsdvfqsdfvqsdfvqs](https://user-images.githubusercontent.com/44909803/129493792-8c16d181-0118-4d0f-b78c-f634e4835025.PNG)

**Comment by pjeby** [comment] 2021-08-15 22:51
What `network_mode` are you using?

**Comment by NhProGamer** [comment] 2021-08-16 06:58
host

**Comment by pjeby** [comment] 2021-08-16 07:43
The only thing I can think of then is that there's an issue with docker or your networking stack.  I'd suggest seeing if you can get a simple tool (such as `socat`) to listen on any of those ports, both inside and outside another host-mode docker container.  That should help narrow down where the problem is.

**Comment by NhProGamer** [comment] 2021-08-16 07:56
okay, thanks

**Comment by pjeby** [comment] 2021-08-28 20:26
Closing this since your instance appears to be up and running now.

**Closed as completed by pjeby** 2021-08-28 20:26 UTC
